---
title: "Introdução ao R Markdown"
author: "Emily Silva Araujo"
date: '2022-05-20'
output: ioslides_presentation
---

## Introdução

-   R Markdown é uma ferramenta contida dentro do Rstudio, a qual te permite desenvolver de forma fácil documentos em formato HTML, PDF e word, desde o R.

-   Com o R Markdown, você pode inserir o código de seus scripts do R dentro de teus documentos ou apresentações.

## O que é o R Markdown?

-   O R markdown é uma integração do código do R com o Markdown.
-   Documentos escritos em R Markdown contém os scripts dentro dele, o que permite ao usuário criar documentos nos quais facilmente se pode visualizar os codigos e o resultados destes (resultados dos testes estatisticos, tabelas e figuras graficas por exemplo).

## Qual a utilidade desta ferramenta?

Originalmente foi pensada para publicar textos na internet de forma mais prática e simples. Entretanto, possue muitas utilidades:  

> -  Criar apostilas didáticas ou livros.

> -  Criar apresentações.  

> -  Ajuda no processo de pesquisa reproduzivel, isto é, outro usuário pode comprovar os resultados do teu trabalho de forma rápida, passo a passo.

> -  Escrever relatórios técnicos com melhor apresentação, de forma simples e didático.  


## Linguagem do R Markdown

## Títulos

- Headings são os títulos.  

- É importante digitar sempre fora dos trechos nos quais você deseja adicionar os códigos.  

- Outro detalhe, digite os # na frente do título, não junto; como vemos no exemplo.    

## Este é um título principal

### Este é um título secundário

#### Este é um título terciário

## Formas de destacar o texto

-   O símbolo de * deixará a frase em formato italico.

-   Importante é lembrar que o símbolo de * deve ser colocado no início e no final da frase.

-   O asterisco deve estar colado na frase.

-   Sempre será necessário usar apenas 1*, uma vez que dois ** indicam outro formato de letra. Esta ação pode ser executada também dentro dos trechos onde será exibido o código do script (chamado chunk).
    Veja o exemplo.

## Listas não ordenadas

abacate, primeiro item na lista

damasco, terceiro item na lista

banana, segundo item na lista

coco, quarto item na lista

## Listas ordenadas

abacate

banana

coco

damasco

## Criar Slides

1) Digitar ## na frente do novo título do slide, **importante não digitar colado**, use um espaço!  
2) Se quiser fazer um slide sem título, use tres ***   
3) Você pode adicionar subtitulos com mais sinais #.  
Exemplo:### Subtitulo;#### Subtitulo ainda menor! 

### Subtitulo  
#### Subtitulo ainda menor!  

## Criando marcadores (pontos)
 
•	Para adicionar marcadores em um slide, use o hifen seguido de um espaço.  
Exemplo: - Acabo de criar um marcador!

- Acabo de criar um marcador!
- Criando marcadores (pontos)

## Criando marcadores (pontos)
•	Para adicionar um sub-item no slide, use quatro espaços e adicione um sinal de +

- Acabo de criar um marcador!  
    + Acabo de criar um sub-item  

## Criando marcadores (pontos)

•	Para adicionar marcadores que vão aparecer um por um, no clikar com: >- marcador interativo!
Veja o exemplo    

> - abacate

> - banana

> - coco

> - damasco


## Links

Para inserir o link pode ser feito os seguintes passos

1)  Escrever o nome do que se deseja colocar o link
2)  Entre colchetes [escreva o que deseja linkar]
3)  Entre parênteses escreva o site onde quer direcionar o link
4)  Apertar Knit na barra de ferramentas e visualizar o resultado

## Links - Exemplo

1)  Estudamos na Universidade Federal do Paraná
2)  [UFPR]
3)  (<https://www.ufpr.br/portalufpr/>)

Deve ficar assim:

Estudamos na Universidade Federal do Paraná - [UFPR](https://www.ufpr.br/portalufpr/)

## Links

Algumas vezes existe a necessidade de inserir muitos links no documento e escrever no formato demonstrado anteriormente pode ficar difícil de visualizar no script.

Uma alternativa seria escrever todos os links em formato de nota de rodapé.

## Links - Exemplo

1)  A palavra que se deseja inserir o link deve estar entre estes simbolos [ ], seguida do número do link que você vai indicar na nota de rodapé.

-**Eu estudei [agronomia](http://www.agrarias.ufpr.br/portal/engenharia-agronomica) no Setor de Ciências Agrarias da UFPR e Mestrado na Pós-graduação em Produção Vegetal, [PRPPG](http://www.prppg.ufpr.br/site/en/ "PRPPG") da UFPR**.

2)  Na nota de rodapé escrever o número do link entre [ ], seguido de dois pontos e o link do site desejado.
    No final, coloque a palavra escolhida entre aspas.

[1]:http://www.agrarias.ufpr.br/portal/engenharia-agronomica "agronomia"  
[2]:http://www.prppg.ufpr.br/site/en/ "PRPPG"
  

## Deve ficar assim:

Eu estudei [agronomia](http://www.agrarias.ufpr.br/portal/engenharia-agronomica) no Setor de Ciências Agrarias da UFPR e Mestrado na Pós-graduação em Produção Vegetal, [PRPPG](http://www.prppg.ufpr.br/site/en/ "PRPPG") da UFPR.

## Novas linhas

Para obter novas linhas é **obrigatório** que se aperte duas vezes o enter no final da frase. Veja o exemplo.

Linha 1
Linha 2 (não cliquei duas vezes no final da frase ou palavra)

Linha 3    
Linha 4  (cliquei duas vezes no final da frase ou palavra)  

## Considerações finais

- Ao principio o novo usuário devera gastar energia para aprender a usar esta ferramenta;    

- Criar uma apresentação em R Markdown requer paciência e persistência, não desanime!    

- Estas aulas apresentam uma introdução ao tema, certamente você deverá buscar informação adicional conforme tua necessidade!    

Para isso, deixaremos literatura!  

## Referências


- Roger D. Peng. Report Wrinting  for Data Science in R.  
     + This book is for sale at http://leanpub.com/reportwriting 

 - Para maiores informações sobre o R Markdown visite o site indicado:  
     + http://rmarkdown.rstudio.com/
     
## Muito obrigada pela atenção!!

**Emily Silva Araujo**    
*araujosemily@gmail.com*  
